### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Swifty-Karel#1]
# 0x00, Fix animation issue
![XCPlayground Issue](https://cloud.githubusercontent.com/assets/10842684/24583831/f95d2a36-1725-11e7-9430-8e35bc53173f.png)

**Comment by ApolloZhu** [comment]
# TODO Queue

- [x] Introduction
- [x] `Playground.current` customizations
- [x] new `ColorScheme`
- [x] Export `Playground.current`
- [x] `"Hello WWDC17"`
- [ ] Examples in Stanford's *Karel the Robot Learns Java*
- [ ] TOC，header/footer，LICENSE
- [ ] README

**Comment by ApolloZhu** [comment]
<img width="1792" alt="Screen Shot 2020-05-06 at 06 37 29" src="https://user-images.githubusercontent.com/10842684/81167960-2183aa80-8f64-11ea-8f85-b017331bad83.png">
